---
- name: Install individual packages with pip
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ spicy_python_packages }}"
  when: >
    spicy_python_packages | length > 0
  environment:
    PATH: "{{ ansible_user_dir }}/.pyenv/shims:{{ ansible_env.PATH }}"
