---
- name: Install grc from package
  apt:
    deb: "{{ spicy_grc_deb_url }}"
  become: yes
  when: >
    "ansible_distribution == 'Ubuntu'" or
    "ansible_distribution == 'Debian'"

- name: Add grc to the oh-my-zsh plugins
  set_fact:
    ohmyzsh_plugins: "{{ ohmyzsh_plugins + [ 'grc' ] }}"
