---
- name: Setup the SHELL
  include_tasks: shell.yml
  when: >
    spicy_shell is defined
    and spicy_shell != "bash"

- name: Setup SSH environment
  include_tasks: setup_ssh.yml
  when: spicy_ssh | bool

- name: Setup PyEnv
  include_tasks: pyenv.yml
  when: spicy_pyenv | bool

- name: Setup GRC
  include_tasks: grc.yml
  when: >
    spicy_grc | bool and
    ("ansible_distribution == 'Ubuntu'" or
    "ansible_distribution == 'Debian'")

- name: Enable Oh My Zsh
  include_tasks: ohmyzsh.yml
  when: >
    spicy_shell == "zsh" and
    spicy_oh_my_zsh | bool

- name: Setup powerline10k as the default theme
  include_tasks: p10k.yml
  when: >
    spicy_shell == "zsh" and
    spicy_oh_my_zsh | bool and
    spicy_p10k | bool
