---
- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "os/{{ ansible_distribution }}/{{ ansible_distribution_release }}.yml"
    - "os/{{ ansible_distribution }}.yml"
    - "os/{{ ansible_os_family }}.yml"
    - "os/{{ ansible_system }}.yml"
    - "os/default.yml"

- name: Setup on Linux
  include_tasks: Linux.yml
  when: "ansible_system == 'Linux'"
