---
- name: "Add pyenv to the oh-my-zsh plugins"
  set_fact:
    ohmyzsh_plugins: "{{ ohmyzsh_plugins + [ 'pyenv' ] }}"

- name: Make sure pyenv is loaded properly
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    create: yes
    block: |
      export PYENV_ROOT="$HOME/.pyenv
      export PATH="$PYENV_ROOT/bin:$PATH
      eval "$(pyenv init -)

- name: Make sure pyenv is loaded properly in ZSH
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.zprofile"
    create: yes
    block: |
      export PYENV_ROOT="$HOME/.pyenv
      export PATH="$PYENV_ROOT/bin:$PATH
      eval "$(pyenv init -)
