---
- name: Import and run the pyenv role
  import_role:
    name: markosamuli.pyenv
  vars:
    pyenv_init_shell: false
    
- name: "Add pyenv to the oh-my-zsh plugins"
  set_fact:
    ohmyzsh_plugins: "{{ ohmyzsh_plugins + [ 'pyenv' ] }}"

- name: Make sure pyenv is loaded properly
  blockinfile:
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    create: yes
    mode: "0644"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
  with_items:
    - ".profile"
    - ".zprofile"
