---
- name: Check if the remote user have SSH keys to install
  ansible.builtin.stat:
    path: "{{ spicy_ssh_keys_folder }}"
  register: spicy_authorized_keys_folder
  delegate_to: 127.0.0.1

- name: Collect SSH keys for the user to install
  set_fact:
    spicy_authorized_keys: "{{ lookup('fileglob', '{{ spicy_ssh_keys_folder }}/*.pub', wantlist=True) }}"
  when: spicy_authorized_keys_folder.stat.exists
  delegate_to: 127.0.0.1

- name: Setup authorized key(s)
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ item }}"
  with_file: "{{ spicy_authorized_keys }}"
  when: spicy_authorized_keys | length > 0

- name: Check if the remote user have private keys to install
  ansible.builtin.stat:
    path: "{{ spicy_private_key_folder }}"
  register: spicy_private_key_folder_stats
  delegate_to: 127.0.0.1

- name: Collect private keys for the user to install
  set_fact:
    spicy_private_key_files: "{{ lookup('fileglob', '{{spicy_private_key_folder}}/*', wantlist=True) | reject('match', spicy_private_key_regex) | list }}"
  when: spicy_private_key_folder_stats.stat.exists
  delegate_to: 127.0.0.1

- name: Debug
  debug:
    msg: "{{ spicy_private_key_files }}"

- name: Keychain | Generate private key list
  set_fact:
    spicy_private_keys: "{{ spicy_private_keys + [ item  | regex_replace('^.*/(.*)$', '\\1') ] }}"
  loop: "{{ spicy_private_key_files }}"
  when: spicy_private_key_files | length > 0

- name: Keychain | Install private keys
  copy:
    src: "{{ spicy_private_key_folder }}"
    dest: ~/.ssh
    owner: "{{ ansible_user_id }}"
    mode: preserve
  when: spicy_private_keys | length > 0

- name: Keychain | Install required packages
  become: yes
  ansible.builtin.package: 
    name: "keychain"
    state: latest
  register: spicy_keychain_installed
  until: spicy_keychain_installed is succeeded
  when: spicy_keychain | bool

- name: Generate list of identities for keychain
  set_fact:
    spicy_keychain_identities: "{{ spicy_private_keys | join(' ') }}"
  when: >
    spicy_keychain | bool and
    spicy_private_keys | length > 0

- name: Keychain | Add private keys to keychain
  set_fact:
    ohmyzsh_keychain_options: "{{ ohmyzsh_keychain_options + [ 'identities ' + spicy_keychain_identities ] }}"
  when: spicy_keychain_identities != ""

- name: "Keychain | Enable keychain for bash"
  lineinfile:
    dest: "~{{ ansible_user_id }}/.bashrc"
    regexp: "eval $(keychain --eval --agents (.*))"
    line: "eval $(keychain --eval --agents ssh {{ spicy_keychain_identities }})"
    state: present
    owner: "{{ ansible_user_id }}"
    create: no
  when: spicy_keychain_identities != ""

- name: "Keychain | Add keychain to the oh-my-zsh plugins"
  set_fact:
    ohmyzsh_plugins: "{{ ohmyzsh_plugins + [ 'keychain' ] }}"
